name: Windows Test & Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows_wheel:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: |
          choco install python --version 3.9.0 --force
          choco install python --version 3.8.5 --force
      - run: |
          ls c:\
          ls c:\python*\
