name: Windows Test & Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows_wheel:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: |
           choco install python3 --version 3.9.0 --no-progress -y --allowmultiple
           choco install python3 --version 3.8.6 --no-progress -y --allowmultiple
           choco install python3 --version 3.7.9 --no-progress -y --allowmultiple
           choco install python3 --version 3.6.8 --no-progress -y --allowmultiple
      - run: get-command python.exe
      - run: |
          ls c:\
          ls C:\hostedtoolcache\windows\Python\3.9.0\x64
          ls C:\hostedtoolcache\windows\Python\3.9.0\
          ls C:\hostedtoolcache\windows\Python\
          ls C:\hostedtoolcache\windows\
          ls c:\Python39
          ls c:\python38
          ls c:\python37
          ls c:\python36
      - run: ls C:\hostedtoolcache\windows\Python

