name: Windows Test & Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows_wheel:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: |
           choco install python3 --version 3.9.0 --no-progress -y --allowmultiple
           choco install python3 --version 3.8.6 --no-progress -y --allowmultiple
           choco install python3 --version 3.7.9 --no-progress -y --allowmultiple
           choco install python3 --version 3.6.8 --no-progress -y --allowmultiple
      - run: get-command python.exe
      - run: |
          ls c:\
          ls c:\python39\python.exe
          ls c:\python38\python.exe
          ls c:\python37\python.exe
          ls c:\python36\python.exe

